// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # The current catalog of scored records
    #
    # + 'limit - Max records to return
    # + offset - Records to skip
    # + return - The current catalog
    resource function get catalog(int 'limit = 20, int offset = 0) returns inline_response_200 {
        int effectiveLimit = 'limit;
        if effectiveLimit > 100 {
            effectiveLimit = 100;
        }
        if effectiveLimit < 0 {
            effectiveLimit = 0;
        }
        int effectiveOffset = offset;
        if effectiveOffset < 0 {
            effectiveOffset = 0;
        }

        Record[]sourceData = currentCatalog();
        int total = sourceData.length();

        int endIndex = effectiveOffset + effectiveLimit;
        if endIndex > total {
            endIndex = total;
        }
        Record[] page = [];
        if effectiveOffset < total {
            page = sourceData.slice(effectiveOffset, endIndex);
        }

        string? next = ();
        if endIndex < total {
            next = string `/catalog?limit=${effectiveLimit}&offset=${endIndex}`;
        }
        string? previous = ();
        if effectiveOffset > 0 {
            int previousOffset = effectiveOffset - effectiveLimit;
            if previousOffset < 0 {
                previousOffset = 0;
            }
            previous = string `/catalog?limit=${effectiveLimit}&offset=${previousOffset}`;
        }

        log:printInfo("catalog served", recordCount = page.length());

        return {
            count: total,
            next: next,
            previous: previous,
            data: page
        };
    }

    # Switch the catalog between full and empty mode
    #
    # + return - returns can be any of following types
    # http:Ok (Mode switched)
    # http:BadRequest (The requested mode is not valid)
    resource function post operations/mode(@http:Payload operations_mode_body payload) returns InlineResponse2001Ok|ErrorBadRequest {
        string requestedMode = payload.mode;
        if requestedMode == "full" {
            catalogMode = "full";
        } else if requestedMode == "empty" {
            catalogMode = "empty";
        } else {
            Error errorBody = {
                code: 400,
                message: "Invalid mode",
                description: string `mode must be 'full' or 'empty', got '${requestedMode}'`
            };
            return <ErrorBadRequest>{body: errorBody};
        }

        log:printInfo("catalog mode switched", mode = catalogMode);

        return <InlineResponse2001Ok>{body: {mode: catalogMode}};
    }
}

public type InlineResponse2001Ok record {|
    *http:Ok;
    inline_response_200_1 body;
|};

public type operations_mode_body record {
    # Catalog mode to switch to
    string mode;
};

public type inline_response_200_1 record {
    # The catalog's mode after the switch
    "full"|"empty" mode;
};

public type inline_response_200 record {
    # total matching records
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Record[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type Record record {
    # Record identifier
    int id;
    # Record name
    string name;
    # Record score
    int score;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};
